### ISSUE TITLE
upgrade to fp-ts@1.0.0

### ISSUE THREAD

**Issue by gcanti** [gcanti/hyper-ts#9]
@leemhenson I just published `fp-ts@1.0.0`, what do you think about upgrading this library?

**Comment by gcanti** [comment]
@leemhenson my plan is to release `hyper-ts@0.2.0` which will be compatible with `fp-ts@0.6.x` and then working on this

**Comment by leemhenson** [comment]
Hey. I'm snowed under with work atm so whatever you want to do is cool with me!
